/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Upsell2V2CaroRouteImport } from './routes/upsell-2-v2-caro'
import { Route as Upsell2RouteImport } from './routes/upsell-2'
import { Route as Upsell1V1220RouteImport } from './routes/upsell-1-v1-220'
import { Route as UpsellRouteImport } from './routes/upsell'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as RoletaEliteTesteRouteImport } from './routes/roleta-elite-teste'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as Downsell2HotRouteImport } from './routes/downsell-2-hot'
import { Route as Downsell2RouteImport } from './routes/downsell-2'
import { Route as Downsell1V1110RouteImport } from './routes/downsell-1-v1-110'
import { Route as DownsellRouteImport } from './routes/downsell'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminFunilRouteImport } from './routes/admin/funil'
import { Route as AuthenticatedWaitingRouteImport } from './routes/_authenticated/waiting'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedQuizRouteImport } from './routes/_authenticated/quiz'
import { Route as AuthenticatedProtocolRouteImport } from './routes/_authenticated/protocol'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProcessingRouteImport } from './routes/_authenticated/processing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const Upsell2V2CaroRoute = Upsell2V2CaroRouteImport.update({
  id: '/upsell-2-v2-caro',
  path: '/upsell-2-v2-caro',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell2Route = Upsell2RouteImport.update({
  id: '/upsell-2',
  path: '/upsell-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell1V1220Route = Upsell1V1220RouteImport.update({
  id: '/upsell-1-v1-220',
  path: '/upsell-1-v1-220',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsellRoute = UpsellRouteImport.update({
  id: '/upsell',
  path: '/upsell',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const RoletaEliteTesteRoute = RoletaEliteTesteRouteImport.update({
  id: '/roleta-elite-teste',
  path: '/roleta-elite-teste',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const Downsell2HotRoute = Downsell2HotRouteImport.update({
  id: '/downsell-2-hot',
  path: '/downsell-2-hot',
  getParentRoute: () => rootRouteImport,
} as any)
const Downsell2Route = Downsell2RouteImport.update({
  id: '/downsell-2',
  path: '/downsell-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Downsell1V1110Route = Downsell1V1110RouteImport.update({
  id: '/downsell-1-v1-110',
  path: '/downsell-1-v1-110',
  getParentRoute: () => rootRouteImport,
} as any)
const DownsellRoute = DownsellRouteImport.update({
  id: '/downsell',
  path: '/downsell',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFunilRoute = AdminFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedWaitingRoute = AuthenticatedWaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizRoute = AuthenticatedQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProtocolRoute = AuthenticatedProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcessingRoute = AuthenticatedProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/downsell': typeof DownsellRoute
  '/downsell-1-v1-110': typeof Downsell1V1110Route
  '/downsell-2': typeof Downsell2Route
  '/downsell-2-hot': typeof Downsell2HotRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/roleta-elite-teste': typeof RoletaEliteTesteRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/upsell': typeof UpsellRoute
  '/upsell-1-v1-220': typeof Upsell1V1220Route
  '/upsell-2': typeof Upsell2Route
  '/upsell-2-v2-caro': typeof Upsell2V2CaroRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/processing': typeof AuthenticatedProcessingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/protocol': typeof AuthenticatedProtocolRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/results': typeof AuthenticatedResultsRoute
  '/waiting': typeof AuthenticatedWaitingRoute
  '/admin/funil': typeof AdminFunilRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/downsell': typeof DownsellRoute
  '/downsell-1-v1-110': typeof Downsell1V1110Route
  '/downsell-2': typeof Downsell2Route
  '/downsell-2-hot': typeof Downsell2HotRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/roleta-elite-teste': typeof RoletaEliteTesteRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/upsell': typeof UpsellRoute
  '/upsell-1-v1-220': typeof Upsell1V1220Route
  '/upsell-2': typeof Upsell2Route
  '/upsell-2-v2-caro': typeof Upsell2V2CaroRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/processing': typeof AuthenticatedProcessingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/protocol': typeof AuthenticatedProtocolRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/results': typeof AuthenticatedResultsRoute
  '/waiting': typeof AuthenticatedWaitingRoute
  '/admin/funil': typeof AdminFunilRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/downsell': typeof DownsellRoute
  '/downsell-1-v1-110': typeof Downsell1V1110Route
  '/downsell-2': typeof Downsell2Route
  '/downsell-2-hot': typeof Downsell2HotRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/roleta-elite-teste': typeof RoletaEliteTesteRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/upsell': typeof UpsellRoute
  '/upsell-1-v1-220': typeof Upsell1V1220Route
  '/upsell-2': typeof Upsell2Route
  '/upsell-2-v2-caro': typeof Upsell2V2CaroRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/processing': typeof AuthenticatedProcessingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/protocol': typeof AuthenticatedProtocolRoute
  '/_authenticated/quiz': typeof AuthenticatedQuizRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/waiting': typeof AuthenticatedWaitingRoute
  '/admin/funil': typeof AdminFunilRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/downsell'
    | '/downsell-1-v1-110'
    | '/downsell-2'
    | '/downsell-2-hot'
    | '/politica-de-privacidade'
    | '/roleta-elite-teste'
    | '/termos-de-uso'
    | '/upsell'
    | '/upsell-1-v1-220'
    | '/upsell-2'
    | '/upsell-2-v2-caro'
    | '/dashboard'
    | '/processing'
    | '/profile'
    | '/protocol'
    | '/quiz'
    | '/results'
    | '/waiting'
    | '/admin/funil'
    | '/admin/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/downsell'
    | '/downsell-1-v1-110'
    | '/downsell-2'
    | '/downsell-2-hot'
    | '/politica-de-privacidade'
    | '/roleta-elite-teste'
    | '/termos-de-uso'
    | '/upsell'
    | '/upsell-1-v1-220'
    | '/upsell-2'
    | '/upsell-2-v2-caro'
    | '/dashboard'
    | '/processing'
    | '/profile'
    | '/protocol'
    | '/quiz'
    | '/results'
    | '/waiting'
    | '/admin/funil'
    | '/admin/login'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/downsell'
    | '/downsell-1-v1-110'
    | '/downsell-2'
    | '/downsell-2-hot'
    | '/politica-de-privacidade'
    | '/roleta-elite-teste'
    | '/termos-de-uso'
    | '/upsell'
    | '/upsell-1-v1-220'
    | '/upsell-2'
    | '/upsell-2-v2-caro'
    | '/_authenticated/dashboard'
    | '/_authenticated/processing'
    | '/_authenticated/profile'
    | '/_authenticated/protocol'
    | '/_authenticated/quiz'
    | '/_authenticated/results'
    | '/_authenticated/waiting'
    | '/admin/funil'
    | '/admin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DownsellRoute: typeof DownsellRoute
  Downsell1V1110Route: typeof Downsell1V1110Route
  Downsell2Route: typeof Downsell2Route
  Downsell2HotRoute: typeof Downsell2HotRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  RoletaEliteTesteRoute: typeof RoletaEliteTesteRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  UpsellRoute: typeof UpsellRoute
  Upsell1V1220Route: typeof Upsell1V1220Route
  Upsell2Route: typeof Upsell2Route
  Upsell2V2CaroRoute: typeof Upsell2V2CaroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upsell-2-v2-caro': {
      id: '/upsell-2-v2-caro'
      path: '/upsell-2-v2-caro'
      fullPath: '/upsell-2-v2-caro'
      preLoaderRoute: typeof Upsell2V2CaroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell-2': {
      id: '/upsell-2'
      path: '/upsell-2'
      fullPath: '/upsell-2'
      preLoaderRoute: typeof Upsell2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell-1-v1-220': {
      id: '/upsell-1-v1-220'
      path: '/upsell-1-v1-220'
      fullPath: '/upsell-1-v1-220'
      preLoaderRoute: typeof Upsell1V1220RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell': {
      id: '/upsell'
      path: '/upsell'
      fullPath: '/upsell'
      preLoaderRoute: typeof UpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roleta-elite-teste': {
      id: '/roleta-elite-teste'
      path: '/roleta-elite-teste'
      fullPath: '/roleta-elite-teste'
      preLoaderRoute: typeof RoletaEliteTesteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downsell-2-hot': {
      id: '/downsell-2-hot'
      path: '/downsell-2-hot'
      fullPath: '/downsell-2-hot'
      preLoaderRoute: typeof Downsell2HotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downsell-2': {
      id: '/downsell-2'
      path: '/downsell-2'
      fullPath: '/downsell-2'
      preLoaderRoute: typeof Downsell2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downsell-1-v1-110': {
      id: '/downsell-1-v1-110'
      path: '/downsell-1-v1-110'
      fullPath: '/downsell-1-v1-110'
      preLoaderRoute: typeof Downsell1V1110RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downsell': {
      id: '/downsell'
      path: '/downsell'
      fullPath: '/downsell'
      preLoaderRoute: typeof DownsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/funil': {
      id: '/admin/funil'
      path: '/funil'
      fullPath: '/admin/funil'
      preLoaderRoute: typeof AdminFunilRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/waiting': {
      id: '/_authenticated/waiting'
      path: '/waiting'
      fullPath: '/waiting'
      preLoaderRoute: typeof AuthenticatedWaitingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz': {
      id: '/_authenticated/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthenticatedQuizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/protocol': {
      id: '/_authenticated/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof AuthenticatedProtocolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processing': {
      id: '/_authenticated/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof AuthenticatedProcessingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProcessingRoute: typeof AuthenticatedProcessingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProtocolRoute: typeof AuthenticatedProtocolRoute
  AuthenticatedQuizRoute: typeof AuthenticatedQuizRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedWaitingRoute: typeof AuthenticatedWaitingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProcessingRoute: AuthenticatedProcessingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProtocolRoute: AuthenticatedProtocolRoute,
  AuthenticatedQuizRoute: AuthenticatedQuizRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedWaitingRoute: AuthenticatedWaitingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminFunilRoute: typeof AdminFunilRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminFunilRoute: AdminFunilRoute,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DownsellRoute: DownsellRoute,
  Downsell1V1110Route: Downsell1V1110Route,
  Downsell2Route: Downsell2Route,
  Downsell2HotRoute: Downsell2HotRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  RoletaEliteTesteRoute: RoletaEliteTesteRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  UpsellRoute: UpsellRoute,
  Upsell1V1220Route: Upsell1V1220Route,
  Upsell2Route: Upsell2Route,
  Upsell2V2CaroRoute: Upsell2V2CaroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
