/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWaitingRouteImport } from './routes/_authenticated/waiting'
import { Route as AuthenticatedUpsellRouteImport } from './routes/_authenticated/upsell'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedQuizRouteImport } from './routes/_authenticated/quiz'
import { Route as AuthenticatedProtocolRouteImport } from './routes/_authenticated/protocol'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProcessingRouteImport } from './routes/_authenticated/processing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWaitingRoute = AuthenticatedWaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUpsellRoute = AuthenticatedUpsellRouteImport.update({
  id: '/upsell',
  path: '/upsell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizRoute = AuthenticatedQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProtocolRoute = AuthenticatedProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcessingRoute = AuthenticatedProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/processing': typeof AuthenticatedProcessingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/protocol': typeof AuthenticatedProtocolRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/results': typeof AuthenticatedResultsRoute
  '/upsell': typeof AuthenticatedUpsellRoute
  '/waiting': typeof AuthenticatedWaitingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/processing': typeof AuthenticatedProcessingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/protocol': typeof AuthenticatedProtocolRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/results': typeof AuthenticatedResultsRoute
  '/upsell': typeof AuthenticatedUpsellRoute
  '/waiting': typeof AuthenticatedWaitingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/processing': typeof AuthenticatedProcessingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/protocol': typeof AuthenticatedProtocolRoute
  '/_authenticated/quiz': typeof AuthenticatedQuizRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/upsell': typeof AuthenticatedUpsellRoute
  '/_authenticated/waiting': typeof AuthenticatedWaitingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/processing'
    | '/profile'
    | '/protocol'
    | '/quiz'
    | '/results'
    | '/upsell'
    | '/waiting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/processing'
    | '/profile'
    | '/protocol'
    | '/quiz'
    | '/results'
    | '/upsell'
    | '/waiting'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/processing'
    | '/_authenticated/profile'
    | '/_authenticated/protocol'
    | '/_authenticated/quiz'
    | '/_authenticated/results'
    | '/_authenticated/upsell'
    | '/_authenticated/waiting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/waiting': {
      id: '/_authenticated/waiting'
      path: '/waiting'
      fullPath: '/waiting'
      preLoaderRoute: typeof AuthenticatedWaitingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upsell': {
      id: '/_authenticated/upsell'
      path: '/upsell'
      fullPath: '/upsell'
      preLoaderRoute: typeof AuthenticatedUpsellRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz': {
      id: '/_authenticated/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthenticatedQuizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/protocol': {
      id: '/_authenticated/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof AuthenticatedProtocolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processing': {
      id: '/_authenticated/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof AuthenticatedProcessingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProcessingRoute: typeof AuthenticatedProcessingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProtocolRoute: typeof AuthenticatedProtocolRoute
  AuthenticatedQuizRoute: typeof AuthenticatedQuizRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedUpsellRoute: typeof AuthenticatedUpsellRoute
  AuthenticatedWaitingRoute: typeof AuthenticatedWaitingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProcessingRoute: AuthenticatedProcessingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProtocolRoute: AuthenticatedProtocolRoute,
  AuthenticatedQuizRoute: AuthenticatedQuizRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedUpsellRoute: AuthenticatedUpsellRoute,
  AuthenticatedWaitingRoute: AuthenticatedWaitingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
